### ISSUE TITLE
jenkins-an

### ISSUE THREAD

**Issue by nik786** [metacloud/molecule#1026]
# Issue Type

- to start jenkins service 
- 

# Molecule and Ansible details

```
ansible --version
ansible 2.4.1.0

molecule --version
molecule, version 2.0.4
```

- Molecule installation method: pip install molecule
- Ansible installation method:  pip install ansible

# Desired Behaviour

Jenkins service need to be started inside of container
# Actual Behaviour (Bug report only)

Jenkins is not getting started inside of container

cat handlers/main.yml
---
# handlers file for ci18
- name: restart jenkins
  command: /etc/init.d/jenkins start
  
 cat molecule/default/Dockerfile
 FROM {{ item.image }}

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y python sudo bash ca-certificates && apt-get clean; fi

RUN wget -qO - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add - && \
    echo 'deb http://pkg.jenkins-ci.org/debian binary/' \
      | tee /etc/apt/sources.list.d/jenkins.list && \
    apt-get update && \
    apt-get install --no-install-recommends -y jenkins

RUN echo "hello world"
EXPOSE 8080 50000

**Comment by retr0h** [comment]
I'm going to need a better bug report.  Please better explain what you're talking bout.

**Comment by nik786** [comment]
when i will execute molecule test that time jenkins container should be created. jenkins service should be started inside of jenkins container.

**Comment by retr0h** [comment]
Molecule isn't really intended to build custom images and test them.  Yes, you can probably do it, but your putting logic into your Dockerfile that requires a systemd compatible image.

Because you are expecting jenkins to be running through systemd, the image you are using should be a systemd container, and likely will need to run in privileged mode.

**Comment by nik786** [comment]
i think it wont then also.I think i have tried earlier with systemd container

**Comment by retr0h** [comment]
Im going to close this issue out.  This isn't a Molecule issue and the bug report is riddled with inconsistencies.  I was able to get Jenkins to install perfectly fine.

Dockerfile

```
FROM {{ item.image }}

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y python sudo bash ca-certificates wget && apt-get clean; fi

RUN wget -qO - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add - && echo 'deb http://pkg.jenkins-ci.org/debian binary/' | tee /etc/apt/sources.list.d/jenkins.list && apt-get update && apt-get install --no-install-recommends -y default-jre jenkins

RUN echo "hello world"
EXPOSE 8080 50000
```

And using a systemd capable image in molecule.yml.

```
platforms:
  - name: instance
    image: solita/ubuntu-systemd:latest
    privileged: True
    command: /sbin/init
```

Since I am not proficient in installing Jenkins this may not be entirely correct, but was able to get Jenkins to start.
