### ISSUE TITLE
Is there a replacement for ~/.config/molecule/config.yml in v2?

### ISSUE THREAD

**Issue by drmrd** [metacloud/molecule#1099]
Prior to version 2.0 it was possible to set default molecule.yml values globally using a `~/.config/molecule/config.yml` file, but judging by the documentation and local testing this isn't still supported. Is there an alternative way to have a global molecule.yml/configuration file that gets merged with the molecule.yml files in each role?

Background: My organization has a large number of roles, and their molecule.yml files share a growing amount of common boilerplate options. We'd like to move the common configuration options out into a molecule.yml file that can be merged with (and overridden by) the individual role molecule.yml files.

**Comment by retr0h** [comment]
That is not possible.

**Comment by drmrd** [comment]
Thanks (as always!) for your prompt reply. Is there a reason why this was removed? Would you be receptive to a PR that provides support for something like this?

**Comment by elliotweiser** [comment]
@drmrd This may not be _exactly_ what you're looking for, but this is how I DRY'ed up some of my Molecule YAML files...

Since Molecule 2+ supports [variable substitution](https://molecule.readthedocs.io/en/latest/configuration.html#variable-substitution), I can source a file to set environment variables prior to running `molecule test`.

References:
* https://github.com/elliotweiser/ansible-osx-command-line-tools/blob/master/molecule/default/molecule.yml#L11-L13
* https://github.com/elliotweiser/ansible-osx-command-line-tools/blob/master/molecule/sierra.sh

In this role, I only maintain one `molecule.yml` file as a template.

All that being said, I'd also like to see a return of that YAML configuration merging feature. Test scenarios could "inherit" some common configuration, but override certain settings where appropriate (in ways not currently covered by variable substitution).

**Comment by retr0h** [comment]
> Thanks (as always!) for your prompt reply. Is there a reason why this was removed? Would you be receptive to a PR that provides support for something like this?

Not at the moment.

**Comment by retr0h** [comment]
If this were to be implemented, I know there have been discussions on ways to DRY up molecule.yml when multiple scenarios exist as well.

We have two use cases.

1. Users who have lots of roles to test, and wish to have common settings across all of their molecule.yml files.
2. Users who have lots of scenarios, and wish to have common settings across all of their scenario molecule.yml files.

Since molecule.yml is in the process of being parsed we cannot rely on moleucle.yml to supply a config loading order, b/c we are loading the config.

It feels like we may want to do the following:

1. Molecule loads its config defaults.
2. Load and merge `~/.config/molecule/config.yml` ontop of config.
3. Load and merge `molecule/default/molecule.yml` ontop of config.
4. If additional scenario are present, load that config ontop of the default scenarios config.

The problem I see with this.

1. Users may not want this behavior.  How do we properly and cleanly allow it to be enabled/disabled?
2. Seems like a lot of work for minimal benefit.  DRY is good, but DRY can also be over done.
