### ISSUE TITLE
Wrong directory for Vagrant/VirtualBox console logs

### ISSUE THREAD

**Issue by sparunakian** [metacloud/molecule#1432]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.6.1
  config file = /home/stephane/.ansible.cfg
  configured module search path = [u'/home/stephane/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/molecule/lib/python2.7/site-packages/ansible
  executable location = /opt/molecule/bin/ansible
  python version = 2.7.15 (default, Jun 27 2018, 13:05:28) [GCC 8.1.1 20180531]
```

```
molecule --version
molecule, version 2.16.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Actual Behaviour (Bug report only)

Create a role, setup Molecule with Vagrant/VirtualBox and run it:

```
molecule init scenario --role-name=testrole --driver-name=vagrant
molecule test --all --destroy=always
```

As Molecule and Ansible are in a virtualenv owned by my user, the execution completed, but in `$VENV_PATH/lib/python2.7/site-packages/molecule/provisioner/ansible/playbooks/vagrant/` there is a log file created by VirtualBox named `ubuntu-xenial-16.04-cloudimg-console.log` with boot logs. If the user running Molecule doesn't have the permissions to write in the Python dir, the execution fails. These logs are configured in the Vagrant images of Ubuntu. Previously these logs where in the `molecule/$SCENARIO` directory in the role, but I don't know what changed this. The problem happens on ArchLinux and CentOS 7.

Let me know if I can be of any help concerning this issue.

Regards

**Comment by retr0h** [comment]
Hi @sparunakian I unfortunately don't have an easy answer for you on this one.  Molecule does recommend to be run as a virtualenv, under that setup users do not have this particular issue.  I do not have a work-a-round to prevent the vagrant driver from logging to that location.  I assume it has something to do with the playbooks being shipped with Molecule, and some sort of a working directory issue.  Anyways if you run a virtualenv you should be okay.

**Comment by wilmardo** [comment]
Might have seen something similar which I haven't backtraced yet so it might not be important.

If I remember correctly the temporary directory for the state etc. was `molecule/$SCENARIO/.molecule` or something similair in the project directory. But it seems it now it has moved to `/tmp/molecule/test/$SCENARIO/`. Might have something to do with the introduction of #1055

**Comment by sparunakian** [comment]
Thank you for your response! If Molecule is used in a virtualenv, the creation of logs in the Python directory isn't very elegant, is it?

**Comment by retr0h** [comment]
> Thank you for your response! If Molecule is used in a virtualenv, the creation of logs in the Python directory isn't very elegant, is it?

let me try one thing.

**Comment by retr0h** [comment]
@sparunakian looks like you can add the following to the platform's section of your molecule.yml to no longer write out this log file.

```
provider_raw_config_args: 
  - "customize ['modifyvm', :id, '--uartmode1', 'disconnected']"
```

**Comment by ianwestcott** [comment]
Hi all,

I was also tripped up by this issue, and while @retr0h's `provider_raw_config_args` suggestion did work, I wanted to take a stab at figuring out the root cause. Based on my investigation, I believe the python-vagrant module isn't being initialized with the proper working directory. 

The python-vagrant module is set up in the `VagrantClient._get_vagrant()` method here: https://github.com/metacloud/molecule/blob/2.18.1/molecule/provisioner/ansible/plugins/libraries/molecule_vagrant.py#L471-L477

That code attempts to set Vagrant's working directory directly via the [`VAGRANT_CWD` environment variable](https://www.vagrantup.com/docs/other/environmental-variables.html#vagrant_cwd), circumventing the python-vagrant module. However, python-vagrant attempts to set its own working directory on initialization: https://github.com/todddeluca/python-vagrant/blob/v0.5.3/vagrant/__init__.py#L171 If the `root` argument isn't passed on init, python-vagrant explicitly sets it to `os.getcwd()`. I suspect that's where the bad path is coming from, though I haven't found a good way to confirm exactly what the working directory is at that time.

In my testing, I was able to resolve this issue by setting the working directory via python-vagrant's `root` argument instead of the `VAGRANT_CWD` env var. I [created a branch with this change](https://github.com/metacloud/molecule/compare/master...ianwestcott:fix_vagrant_cwd), but I haven't managed to get the test suite working yet. Once I do I'll post a PR, but I welcome any feedback on this solution in the meantime.
