### ISSUE TITLE
Molecule status is too slow (vagrant provider)

### ISSUE THREAD

**Issue by rgreinho** [metacloud/molecule#181]
The ``molecule status`` command, used with the vagrant provider is too slow. It takes an average of 3s to execute. This is particularly annoying as this command is the one providing the dynamic arguments during the bash completion.

Would it be possible to extract the information directly from the molecule configuration file rather than querying vagrant for this?

**Comment by conorsch** [comment]
Is running `vagrant ssh-config` any faster? The slowness you're describing is likely vagrant itself. Reading machine information from the YAML files on disk isn't as accurate, since the status info displays dynamic information such as machine state (e.g. "running"). 

Great point about the bash completion though. Can you provide example commands for what you're trying to tab-complete? If it's just machine names, then it would make sense to read them from the local YAML files.

**Comment by rgreinho** [comment]
Yes you're right, the slowness totally comes from vagrant itself.

The tab-completion for any command that can get the dynamic arguments through ``molecule status`` [0] is too slow (~3s to complete). This does not provide a good user experience.

As we are just looking for platforms, providers, or hosts, I think I could just use the molecule.yml instead of using the provider to retrieve this info.

---
[0] | https://github.com/metacloud/molecule/blob/master/assets/bash_completion/molecule.bash-completion.sh#L9-L19

**Comment by retr0h** [comment]
@rgreinho Is this still an issue?
