### ISSUE TITLE
`molecule test` is successful if the last test passes (even though another one failed)

### ISSUE THREAD

**Issue by techraf** [metacloud/molecule#183]
With:

```
    sequence:
      - idempotence
      - verify
```

If  Specinfra tests pass, even if idempotence test failed, `molecule` returns exit code 0.

With:

```
    sequence:
      - verify
      - idempotence
```

If idempotence test passes, even if Specinfra tests failed, `molecule` returns exit code 0.

Is it by design?

**Comment by kireledan** [comment]
The return code depends on the success of the last running item. It definitely shouldn't return 0 if one of those fails because idempotence will return 1 if the idempotence test fails. I would say this is not as intended and will fix this so that ```test``` will return the non-zero error code if it encounters one.

**Comment by retr0h** [comment]
This should now be resolved.
