### ISSUE TITLE
100 chars is too short for spec files 

### ISSUE THREAD

**Issue by sandinak** [metacloud/molecule#2]
I have paths and other tests that end up being longer than 100 characters.  For instance
'''
pec/entity_spec.rb:68:100: C: Line is too long. [116/99]
describe file('/ xxx/xxxxx/xxxxxx/xxxx_xx/xxxx/xxx/xxxxxx/xxx/xxxxxxxx-xx/ssl/xxxxxxxx.xxxxxxxxxx.xx.xxxxxxxxx.xx.crt') do
                                                                                                   ^^^^^^^^^^^^^^^^^
spec/entity_spec.rb:72:100: C: Line is too long. [100/99]
  its(:content) { should match(/MIIxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/) }
'''
Need to up that to twitter spec at least (140 chars ;)

**Comment by retr0h** [comment]
Unfortunately, no matter what number we pick here, someone will not like it.  [RuboCop](http://batsov.com/rubocop/), has adopted the community driven [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide).  However, I do not see anything specific to line length numbers in the spec.

Since these [cops](https://github.com/bbatsov/rubocop#cops) can be changed or disabled, feel free to submit a PR to ansible-sytem's `.rubocop.yml` with:

```
LineLength:
  Enabled: false
```

**Comment by retr0h** [comment]
Actually let me think this over.  Rubocop, will probably only search for a `.rubocop.yml` form the current directory.

**Comment by retr0h** [comment]
I'm leaning towards having the user manually create a `.rubocop.yml` that meets their requirements around linting vs us managing a default one.

So if you don't like the long lines, I suggest creating a `.rubocop.yml` with something like the following in the base of your role.

```
LineLength:
  Enabled: false
```

**Comment by sandinak** [comment]
I've done this to get the role working .. however i think that many people will have paths that will require this setting and this fix is a bit nebulous .. i'd recommend disabling it entirely as the constraint isn't useful to this application.

**Comment by retr0h** [comment]
I don't have a problem with this.  I actually like this requirement.  However, if people don't they can disable just as you did.

**Comment by dhutty** [comment]
Please add a note about this to the molecule docs – or even just a link to an existing discussion of .rubocop.yml. Perhaps we should have a Tips/Conveniences section (both for molecule directly and for the tools molecule uses: rubocop in this case, but also, serverspec/testinfra/vagrant/etc). Since the whole point of molecule is to reduce the barrier for testing Ansible roles as part of the development process, it’s at least partly an educational project as well as a tool project.
