### ISSUE TITLE
Ability to target docker hosts

### ISSUE THREAD

**Issue by retr0h** [metacloud/molecule#300]
We cannot [target](https://github.com/metacloud/molecule/blob/master/demo/molecule/tests/test_demo1.py#L1-Lundefined) docker hosts in testinfra like we can when using the ansible backend.
This was discovered while creating #298.

The problem is due to our docker driver passing all hosts to testinfra via the `--hosts` flag.  This forces all test files to execute across all hosts.

**Comment by retr0h** [comment]
Raised upstream https://github.com/philpep/testinfra/issues/120

**Comment by rcuza** [comment]
It looks like philpep/testinfra#120 was closed but the `--host` option in molecule does not appear to be a feature for `verify`. Is there a reason something like `molecule verify --host bionic` cannot work? If there isn't, I'll open an issue and investigate making a pull request.

This would be helpful for me to debug issues with roles for a particular OS version. During 
a debugging session, I could use this flag to just check the OS that had a problem instead of testing everything.

**Comment by lwm** [comment]
> If there isn't, I'll open an issue and investigate making a pull request.

go go go go go go go :rocket: :rocket: :rocket: :rocket:

**Comment by rcuza** [comment]
#1731 

@retr0h, @lwm - There seems to be a number of different ways that this was asked for, but I couldn't tell if there was a technical reason for not doing it or a project resource reason. I'll see what I can find out.

If you have suggestions for how to improve the wording of #1731, please let me know in that ticket.
