### ISSUE TITLE
Goss support

### ISSUE THREAD

**Issue by freeseacher** [metacloud/molecule#324]
https://github.com/aelsabbahy/goss looks very interesting
Can you please add support for running goss for tests ?

**Comment by aelsabbahy** [comment]
That would be neat. I'm going on vacation, so I can't put in code anytime soon. But feel free to ping me with any questions/concerns on how to integrate Goss.

One notable difference is that Goss is required on the target machine, it doesn't run over `ssh` like serverspec and testinfra.. not sure if that'll be challenging for your integration or not, but it's very simple to install/run.

**Comment by retr0h** [comment]
I have no plans to implement this support any time soon.  Will likely need to happen from someone in the community.

**Comment by kireledan** [comment]
I kinda wanna take a try at this to learn about Goss so I might tinker with this over the weekend.

**Comment by freeseacher** [comment]
@kireledan any news ?

**Comment by kireledan** [comment]
I have not had much of a chance to look at this since school started back up again. But if anyone else wants to tackle it before I can get the chance, feel free to.

**Comment by retr0h** [comment]
Actually, I'm not all that interested in adding support for every test framework.  What we have I believe is adequate, and molecule is fairly opinionated.  I'd actually prefer everyone use testinfra anyways.

The ability to access ansible facts/variables inside the tests is a plus, and ability to target ansible hosts/groups is even more important.  This is one reason testinfra is the default.  Having to support the latter with goss, would end up meaning molecule has to implement this functionality, so that it can execute the goss tests locally on the groups of servers.

For now I'm going to recommend against new verifiers, so we can concentrate on improving the core.

**Comment by retr0h** [comment]
BTW this is not a ding on the quality of goss.  I think the project is amazing, I simply want to concentrate on improving the core of molecule.  We still need to substantially rewrite the config, and improve things across the board.  We can revisit this at a later time.

**Comment by retr0h** [comment]
👍 for goss support 👎 no support

**Comment by retr0h** [comment]
This could actually be implemented today in playbook.yml.  However, this wouldn't be implemented in a way where `verify` would work like the other verifiers.

If we were to implement this at some point in the future, we would probably want to invoke our Ansible Playbook class to execute playbooks.  These playbooks can then target various host or groups to test (much like serverspec/testinfra can).  These playbooks could live under `tests/`,  as long as they don't end in .py, they would not be picked up by testinfra.

We would just leverage the [goss-ansible library](https://github.com/indusbox/goss-ansible), much like we do with the idempotence callback.

**Comment by retr0h** [comment]
I'll prob take a look at this later in the week.

**Comment by freeseacher** [comment]
tnx

**Comment by retr0h** [comment]
@freeseacher @aelsabbahy added very rudimentary goss support in #430.

**Comment by freeseacher** [comment]
tnx. i will try to use it later.
