### ISSUE TITLE
Is it possible to use the ask_sudo_pass variable with Molecule?

### ISSUE THREAD

**Issue by YPCrumble** [metacloud/molecule#478]
It appears in old versions of the documentation that it was possible to use Ansible's `ask_sudo_pass` flag with Molecule. However, with the latest version of Molecule the program hangs on the following step when I add `ask_sudo_pass: True` to the `ansible:` portion of `molecule.yml`. 

```
--> Starting Ansible Run ...
Using .molecule/ansible.cfg as config file
```

My use case is that I'm running a role that creates a non-root sudo user and a password for this user. The first time I run the playbook I run it as root, but for any idempotency test I would need to include a sudo password on the second run. Is this possible using Molecule or should I simply skip the idempotency test for this role?

**Comment by retr0h** [comment]
Hi @YPCrumble.  We really haven't given this particular workflow much thought.  The docs did originally reference `ask_sudo_pass`, but that was mostly b/c we were referencing all the flags passed to ansible.  We actually don't support such a use case, since molecule is intended to be used in CI as well, and CI would have difficulties with user provided input.

This is a fairly tricky use case, and I'm not entirely sure how to tackle it ATM.  We would also run into issues with additional flags (`--ask-vault-pass`, `--ask-su-pass`, `--ask-become-pass`).

**Comment by YPCrumble** [comment]
@retr0h makes sense - thanks for your response! Closing

**Comment by retr0h** [comment]
I'll repoen this for now.  Maybe we can come up with something, but it's a fairly non-standard use case atm.

**Comment by YPCrumble** [comment]
@retr0h thanks. A tangential question that I'm not sure whether to add as a separate issue is how should I best test a playbook that has several roles? Is Molecule designed to test only one role at a time or should I use the `roles:` directive in `playbook.yml` to test all roles in the playbook at once? 

It doesn't appear that there is a way to recursively find the `playbook.yml` in each role and test each role via one call to `molecule test` from the parent directory if I setup a separate test in each role.

**Comment by retr0h** [comment]
@YPCrumble Molecule is intended to test a single role in isolation.  However, if you wish to test more roles in combination, that can be accomplished.

I generally create a new repo, which has a molecule.yml that leverages the [requirements.yml](http://molecule.readthedocs.io/en/stable-1.11/configuration.html?highlight=requirements#role-requirements).  The molecule.yml can then reference and converge multiple roles, and testinfra can assert the outcome.

**Comment by retr0h** [comment]
@YPCrumble Would you be interested in trying an experimental molecule branch, to see if this does what you like?

If you install the following [branch](https://github.com/metacloud/molecule/tree/enhancement-478) and install [molecule from source](http://molecule.readthedocs.io/en/stable-1.11/contributing.html#installing-from-source).

Adding the following to molecule.yml.

```
ansible:
  interactive:
    ask_sudo_pass: True
    password: foo
```

**Comment by retr0h** [comment]
@YPCrumble I'm probably not going to support this at the moment.  It's a fairly dirty undertaking, and would prefer to focus on improving the core of molecule, and work towards scenario based testing.  If you feel this is a huge issue, please re-open.

I performed an [initial prototype](https://github.com/metacloud/molecule/tree/enhancement-478), but things get weird pretty fast when running `test`, `converge`, `idempotence` workflows.

**Comment by RanabirChakraborty** [comment]
Hello @retr0h I know it's late as this query was from 2016. I'm aware of the fact that molecule is generally used for CI and it would be difficult for the user to provide the input.
But I think providing the privilege to use the ask_sudo_pass variable with Molecule would be great because though we can test our roles in VM but using molecule gives a better experience. 
Though not sure will be feasible or not as I guess probably there can be other ways to achieve the same thing.
