### ISSUE TITLE
Stack trace when rubocop isn't installed

### ISSUE THREAD

**Issue by abrown-sg** [metacloud/molecule#580]
It might be nice to catch this exception and print a pretty message.

```
▶ molecule verify
--> Executing rubocop on *.rb files found in spec/.
Traceback (most recent call last):
...
sh.CommandNotFound: rubocop
```

**Comment by retr0h** [comment]
Providing sh a stderr and stdout function, will always make sh display an error, since the function is executed.

This does not allow us to perform a try/catch pattern to squelch output.

We need to entirely rethink how we are dealing with logging and printing of messages in molecule.  I'm not entirely sure we even need to use a logger.
