### ISSUE TITLE
Support for BATS (bash automated test suite)

### ISSUE THREAD

**Issue by pgporada** [metacloud/molecule#647]
# Issue Type

- Feature request

# Desired Behaviour

Being able to use the bash automated test suite. https://github.com/sstephenson/bats

Personally I use this over serverspec/testinfra because I am a shell guy at heart. Here's an example using TK to run BATS. https://github.com/pgporada/ansible-role-nomad/blob/master/test/integration/default/bats/01_nomad.bats

**Comment by retr0h** [comment]
Hi @pgporada I appreciate the request but this isn't something we will be supporting.  I'm actually on the fence about us even supporting Goss.  This project is maintained by a small team, and fairly opinionated.  Supporting various drivers, verifiers, etc.. is time consuming, especially since this project grew from our needs, not the community's needs.

For now I'm going to close this.  Do appreciate your time to request such a feature.

**Comment by pgporada** [comment]
If I figure out how to implement a test suite, will you take a PR?

**Comment by retr0h** [comment]
@pgporada What ends up happening is we get bug reports on features we never end up using.  Hard to say.  Possibly?  For example the OpenStack driver is a tough one.  While we are an OpenStack shop, we actually dont use the OpenStack driver.  Verifying fixes and features is difficult.  However, we will be switching to that driver in the next few months.

**Comment by tterranigma** [comment]
Sorry to post on such and old issue, but I didn't want to open a new one just to ask.

Would it make sense to have a shell verifier that would essentially build a shell command to use? For instance:

```yml
...
verifier:
  name: shell
  command: bats tests.bats
  lint: <another shell command>
```
