### ISSUE TITLE
BDD: support for molecule

### ISSUE THREAD

**Issue by gogskrish** [metacloud/molecule#664]
# Issue Type

   Do we have cucumber BDD support in molecule. am expecting we can have a "cucumber" verifier which will trigger the test from feature file.

- Bug report
- Feature request

# Molecule and Ansible details

```
ansible --version
molecule --version
```

- Molecule installation method: One of source, pip
- Ansible installation method: One of source, pip, OS package

# Desired Behaviour

Please give some details of the feature being requested or what
should happen if providing a bug report.

# Actual Behaviour (Bug report only)

Please give some details of what is actually happening.
Include a [minimum complete verifiable example](http://stackoverflow.com/help/mcve) with
output of running `molecule --debug`.

**Comment by retr0h** [comment]
@gogskrish molecule is fairly opinionated.  To be honest, we have goss and serverspec as additional verifiers, but the latter is only there due to us internally using serverspec first.

I don't envision molecule being an all encompassing framework, that supports numerous verifiers.  A small group of people (mostly me) maintain molecule.  I truthfully do not have the bandwidth  to maintain additional verifiers.

**Comment by retr0h** [comment]
I suggest holding off until molecule v2 lands (no date yet).  Adding additional verifiers will be easier.
