### ISSUE TITLE
Add yamllint as a verifier 

### ISSUE THREAD

**Issue by bbaassssiiee** [metacloud/molecule#869]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.3.1.0
  config file = /Users/bas/code/CI-Server/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
molecule --version
molecule, version 1.25.0
```

- Molecule installation method: One of source, pip
pip
- Ansible installation method: One of source, pip, OS package
pip
# Desired Behaviour

yamllint does not only check for syntax validity, but for weirdnesses like key repetition and cosmetic problems such as lines length, trailing spaces, indentation, etc.
https://github.com/adrienverge/yamllint

# Actual Behaviour (Bug report only)

Please give some details of what is actually happening.
Include a [minimum complete verifiable example](http://stackoverflow.com/help/mcve) with
output of running `molecule --debug`.
N.A.

**Comment by retr0h** [comment]
@bbaassssiiee good suggestion. This will get rolled into v2 Molecule.  Trying to determine where it makes sense, since v2 implements a lint section of the config and runs ansible-lint.  I'm thinking yamllint will always run, similar to how flake8 always runs when using the testinfra validator.

Need to think this one through a bit thought.  I hate overloading these things.
