### ISSUE TITLE
Add option to use Ansible's Dynamic Inventories

### ISSUE THREAD

**Issue by senorsmile** [metacloud/molecule#956]
# Issue Type

- Feature request

# Desired Behaviour

Support dynamic inventories

This was previously mentioned in https://github.com/metacloud/molecule/issues/99 .

We would really like to use molecule for all of the testing scenarios available.  This includes not just testing individual roles, but actually testing real node types.  Unfortunately, we cannot currently do that without our dynamic inventory (which feeds from our Central DB of nodes).  There are many settings for several different dependent roles that are set by different teams.  

Our specific use case involves a node type (let's say a web, backend and db) which have lots of variables defined in our central DB, accessible to ansible only via a dynamic inventory script.  We would like to be able to specify a particular node for testing (let's say web01), and let molecule spin up a test version of that node in AWS, run Ansible, Idempotence checks and testinfra to verify that new versions of Ansible roles and new versions of the App are good to go.

**Comment by aroundthecode** [comment]
+1
For both The dynamic inventory and the real server testing :)

**Comment by alainchiasson** [comment]
I remember a discussion like this in my Chef days, in test kitchen, whenever the question of testing multiple machines came up - The developers talked about it being a "unit test" for recipes (analogue to ansible roles) - and if you needed multiple machines to run test "you were doing something wrong" (their words !) 

In my opinion (and only mine) the request to support dynamic inventories (as described above) seems to place molecule at a higher level - closer to integration testing or deployment testing. Not a bad thing - just different from how I use it today. My current use of molecule is testing a role in isolation as independently as possible - the playbooks in the scenarios define the different use cases of the roles. 

What you are describing sounds more like you are testing the play or playbook or even the entire deployment pattern.

Maybe it would make sense to define a higher level testing framework ? Or define a higher level "role" ( deployment ?)  in molecule so it can move there ? 

I will add that I am somewhat new to ansible and I do have an opinionated view that may be different :-)

**Comment by aroundthecode** [comment]
just to give my 2 cents: 

at the moment I'm using molecule to test the role in isolation with docker and multiple distro, to avoid regressions and have role "coverage" (hope one day to have a report of REAL coverage, but this is another topic) and a linux distro compatibility matrix. This could be considered the role "unit test" in a sort of Test Driven Development of ansible role.

But, on the other hand, I'm re-using a subset of the tests written for "unit test" (using pytest mark to label them) with some additional ad-hoc tests to run also smoke tests on real server after deploy.
Also in this case I'm using molecule with a dedicated scenario running with the custom driver to connect to the real server via ssh-ansible.
This allows me to check that the server deploy is fine and my Continuous Delivery chain can continue since all tests are green.

On my personal view molecule is a good tool to manage both approach, mainly because it allows me to write tests once and use them both for unit tests in isolation and smoke tests in real deploy.

**Comment by retr0h** [comment]
I haven't looked at this yet.  However, Ansible's default behavior is to execute a script that lives in the inventory path.  So when you run `molecule --debug` you will see the inventory path it is using.  If an executable script lives in there, Ansible will load it.  Example below.

```
/Users/jodewey/.pyenv/versions/molecule2-env-2.7.13/bin/ansible-playbook --inventory=/Users/jodewey/git/molecule_2/test/scenarios/driver/docker/molecule/default/.molecule/ansible_inventory.yml --diff /Users/jodewey/git/molecule_2/test/scenarios/driver/docker/molecule/default/playbook.yml -vvv
```

So if you drop a file in the path identified by `--inventory` it should work.   Ansible 2.4 now supports multi-inventory sources, which means we can specify more than one `--inventory` flag.  I have not looked into this yet, or figured out a clean way to implement this into Molecule.

Here is the deal though.  If you do use a dynamic inventory script, things are going to get weird quick, if you supply host inventory, since Molecule manages that internally.  I don't anticipate issues, if you're setting variables through the plugin, but I would steer clear of host inventory.

**Comment by retr0h** [comment]
Now, I think you might be able to get away with what you're trying to do if you use the delegated driver along with passing an additional `--inventory` directive to ansible-playbook through molecule.yml.

This would allow you to ping your CM and converge the role.  However, the delegated driver assumes you will provision the instances yourself.  In the case of dynamic inventory testing, this might be what you want though.

**Comment by retr0h** [comment]
I'm not going to implement this for the time being.  The effort involved to implement this would benefit only the minority.  I also don't believe there is a good way to implement this, such that the dynamic inventory doesn't affect the users use of Molecule.

This decision may be reevaluated in the future.
